### ISSUE TITLE
Extload doesn't work

### ISSUE THREAD

**Issue by mega-micro** [devicefuture/atto#41]
Such words like "broadcasting.send" SOMETIMES highlight. Atto saw it, like hours ago, but now it doesn't. Extload also just doesn't work, it's not supported or something? Why? I can provide more information if needed.

**Comment by James-Livesey** [comment]
Happy to help! Seems like you're having some strange issues... Using the `broadcasting` extension is working for me, though.

From what I hear with the specific issue you're facing, you might want to try emptying your browser cache and hard reloading. The way to do this varies between browsers — on Chrome, open DevTools (press <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd>) and then go back to atto and right-click the refresh button in Chrome, before selecting **empty cache and hard reload**.

If you're able to upload any screenshots of the issues you're facing, that might help so I can see what's going on. If you could provide me with your OS and browser versions and any JavaScript error logs that are shown in DevTools, that would also be appreciated!

You might also want to refer to the [example programs in the atto documentation for the `broadcasting` extension](https://atto.devicefuture.org/docspopout.html?page=docs/extensions/builtin/broadcasting.md) as they are known to be working fine.

Just to note that the atto broadcasting services are provided by a web server that currently goes to sleep after a while and spins up on-demand, and so an initial call to `broadcasting.host` may take up to a minute to finish in some cases — though I don't think this relates to the issues that you're having.

**Comment by mega-micro** [comment]
Thanks! The hard reset actually fixed it. I don't know why it broke though, but maybe it won't occure anymore - I don't remember extload working before.
> You might also want to refer to the [example programs in the atto documentation for the `broadcasting` extension](https://atto.devicefuture.org/docspopout.html?page=docs/extensions/builtin/broadcasting.md) as they are known to be working fine.
The example were also breaking immidetaly after seeing "extload", "broadcast" or etc.

**Comment by James-Livesey** [comment]
No worries — glad it's working for you now! The browser cache can be a bit of a pain sometimes... If you come across this problem again, please do feel free to let me know!

**Comment by mega-micro** [comment]
Yep, for some reason it keeps breaking and I should do a reset everytime. This is the only thing I know right now.

**Comment by mega-micro** [comment]
I tried testing it multiple times, this is how DevTools outputs differ:

After a normal reset (devtools doesn't work in that case):
![atto devtools 1](https://user-images.githubusercontent.com/130433335/231360424-18d2bdf1-f030-48a7-ba39-b8e543ff8d8b.png)
Cache reset and hard reset:
![atto devtools 2](https://user-images.githubusercontent.com/130433335/231360455-952e9990-feea-41a2-9329-6c80d651cd1b.png)
Should I reopen the issue?

**Comment by James-Livesey** [comment]
The errors and warnings I can see in DevTools are what I get too, so they shouldn't be related to the issue you're having. If you can take any screenshots of your atto code/syntax highlighting problems that you've seen and send them over, then I can reopen the issue and might be able to try and work out a solution to things that are going wrong (along with what version of Chrome you have/the OS you're running)!

**Comment by mega-micro** [comment]
Version: latest, 112.0.5615.121 (Official build), (64 bit)
Computer:
- Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz   2.81 GHz
- 16,0 GB RAM (15,9 GB free)
- 64 bit

After a normal refresh:
<img src="https://user-images.githubusercontent.com/130433335/232341461-7195efaf-9c87-4cc4-aa0a-9da605f8ca88.png" alt="atto devtools 5" width="400">
After clearing cache and hard reset:
<img src="https://user-images.githubusercontent.com/130433335/232341467-d454ea94-0bae-4799-afd1-58c6cc8249a9.png" alt="atto devtools 6" width="400">

**Comment by James-Livesey** [comment]
Okay, I reckon that it might be something to do with the service worker that's preferring an old version of atto from when attoX didn't exist. Any invalid command is errored with `Unexpected end of line` as atto expects a variable assignment expression here (eg. in this case `extload=5`), as can be seen in the example below:

![image](https://user-images.githubusercontent.com/42580341/232343697-417e2173-75af-4264-876c-01cb2a75089e.png)

I've invalidated the service worker's version so it should hopefully be forced to redownload everything. If you do a hard refresh at your end, it should now _hopefully_ be fine from here on! If not, then in DevTools, go to the **Application** tab at the top, then **Service Workers** section, then press **Unregister** — that should do the trick (service workers can be weird sometimes).

**Comment by mega-micro** [comment]
Thanks!! It actually worked. Now extload works and `for i=0 to 50:draw random*500,random*500:next` works correctly, which means that atto is in the latest version now.
