### ISSUE TITLE
"random" in "draw" works incorrectly

### ISSUE THREAD

**Issue by mega-micro** [devicefuture/atto#42]
It looks like the old location is also randomized, but it shouldn't be. If you type:
`10 for count=1 to 100`
`20 draw random*500,random*500`
`30 next`
The lines will NOT be connected to each other. But if after that you type:
`11 x=random*500`
`12 y=random*500`
`20 draw x,y`
`renum`
It will work correctly.
![atto devtools 3](https://user-images.githubusercontent.com/130433335/232340382-47fd279e-e3b0-4474-9185-836875edd0c4.png)
![atto devtools 4](https://user-images.githubusercontent.com/130433335/232340384-978d3925-c0ab-40b8-9082-66fd814cce68.png)

**Comment by James-Livesey** [comment]
Just fixed this, so it should work now! Basically, the arguments passed to commands such as `draw` ended up getting evaluated multiple times (which is a problem when expressions containing `random` always change), so I made sure they only get evaluated once. There were a bunch of other commands that are affected by this issues as well, so I fixed all of them, too.

[Test case program](https://atto.devicefuture.org/?code=5%20cls%0A10%20for%20count%3D1%20to%2010%0A11%20x%3Drandom*500%0A12%20y%3Drandom*500%0A20%20draw%20random*500%2C%20random*500%0A30%20next%0A40%20goto%2040&runmode=list):
```basic
5 cls
10 for count=1 to 10
11 x=random*500
12 y=random*500
20 draw x, y
30 next
40 goto 40
```

Thanks for reporting the issue! The atto.devicefuture.org site should update shortly, and you might need to clear your browser cache.

**Comment by James-Livesey** [comment]
(Also — not sure if it was intentional on your part — but I appreciate how the bad and good test cases are coloured red and green respectively 😉)

**Comment by mega-micro** [comment]
Yes, if I don't do a hard reset, the bug will still weirdly be there.
